### PR TITLE
Add addons : bnx2 for DS3622XS+ and DS3617XS

### PR DESCRIPTION
**Pull request by the-leaf**
Test on DELL Poweredge T410 it's work

### CODE REVIEW

**Comment by fbelavenuto** [comment]
Hi, for common modules I use the arpl-modules repository. These drivers already exists:
https://github.com/fbelavenuto/arpl-modules/blob/main/broadwell-4.4.180/bnx2.ko
https://github.com/fbelavenuto/arpl-modules/blob/main/broadwellnk-4.4.180/bnx2.ko

Existing drivers don't work without this addon?

**Comment by the-leaf** [comment]
yes it doesn't work

**Comment by fbelavenuto** [comment]
Okay, so I'll put it in the arpl-modules repository, if you want to make a pull request in the repository 'arpl-modules' to have your name in the contributions, feel free.

**Comment by the-leaf** [comment]
Okay

**Pull request closed without merging**
