### PR TITLE
Adding DS923+

### PR DESCRIPTION
**Pull request by fbelavenuto**

### CODE REVIEW

**Comment by Brian099** [comment]
Vmware install failed? no disk found.

**Comment by fbelavenuto** [comment]
> Vmware install failed? no disk found.

Try to update modules, rebuild and try again

**Comment by Brian099** [comment]
updated, still same. and netcard must be changed to e1000e, or the DSM can not be found, with default e1000, thanks.

**Comment by Brian099** [comment]
V1 b6 solved, thanks.

**Pull request merged**
